backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Articoli del Blog"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the title"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Descrizione", name: "description", widget: "text"}
      - {label: "Copertina", name: "cover", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Bozza", name: "draft", widget: "boolean", default: true}
      - {label: "Contenuto", name: "body", widget: "markdown"}

  - name: "terapie"
    label: "Terapie"
    folder: "content/servizi/terapie"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the title"}
      - {label: "Introduzione", name: "intro", widget: "text"}
      - {label: "Ordine", name: "order", widget: "number", default: 0}
      - {label: "Descrizione", name: "description", widget: "markdown"}
      - {label: "Benefici", name: "benefici", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "string"}}
      - {label: "Come funziona", name: "come_funziona", widget: "markdown"}
      - {label: "FAQ", name: "faq", widget: "list", fields: [{label: "Domanda", name: "domanda", widget: "string"}, {label: "Risposta", name: "risposta", widget: "markdown"}]}

  - name: "aree"
    label: "Aree di Intervento"
    folder: "content/servizi/aree"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version of the title"}
      - {label: "Introduzione", name: "intro", widget: "text"}
      - {label: "Ordine", name: "order", widget: "number", default: 0}
      - {label: "Descrizione", name: "description", widget: "markdown"}
      - {label: "Benefici", name: "benefici", widget: "list", field: {label: "Beneficio", name: "beneficio", widget: "string"}}
      - {label: "Come funziona", name: "come_funziona", widget: "markdown"}
      - {label: "FAQ", name: "faq", widget: "list", fields: [{label: "Domanda", name: "domanda", widget: "string"}, {label: "Risposta", name: "risposta", widget: "markdown"}]}

  - name: "testimonials"
    label: "Testimonianze"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nome", name: "author", widget: "string"}
      - {label: "Ruolo", name: "role", widget: "string", required: false}
      - {label: "Contenuto", name: "content", widget: "text"}
      - {label: "Valutazione", name: "rating", widget: "number", min: 1, max: 5, default: 5}
      - {label: "Ordine", name: "order", widget: "number", default: 0}
      - {label: "Attivo", name: "active", widget: "boolean", default: true}

